# 基本设置
[base]
# 服务器id
server_id=10251
# 游戏id
game_id=251
# peer 没通信多久清理(秒)
peer_clean_timeout_sec = 300
# 缓存的account信息 多久没访问清理(秒)
account_cache_cleans_timeout_sec = 300

[master]
# 服务器ip
addr = "127.0.0.1:7450"
# 服务器名
service_name = "master"
# 服务器验证key
verify_key = ""
# 服务器请求超时时间
request_out_time_ms = 15000


# 代理监听设置
[proxy_listen]
# the local IP address and port that the service listens on.
addr = "0.0.0.0:10251"
# used to verify whether the service_name in the client configuration is correct
service_name = "game"
# used to verify whether the verify_key in the client configuration is correct.
verify_key = ""
# the timeout period for the server to request the client
request_out_time = 5000
# the existence time of the client peer session. If it exceeds this time, the client peer will be cleared
session_save_time = 5000


